### ISSUE TITLE
No 'catalog' option available

### ISSUE THREAD

**Issue by CosmicQ** [ibm-cloud-docs/cloud-monitoring#15]
Upon logging into IBM Cloud, my default view is the Dashboard.  There is no "Catalog" option anywhere.  Neither the 'Cloud Foundry' or 'DevOps' menu selections offer the ability to filter on "DevOps".

**Comment by CosmicQ** [comment]
Found it.  It may be better to add "Catalog (located at the top of the screen)"

Also, it looks like the "DevOps" category was renamed to "Developer Tools".

**Comment by lopezdsr** [comment]
service deprecated
